Parser.scalaでparsing.conbinatorを導入しました
ichikawapc/config-parse pull request #24
Opened 2023-11-12 15:20 UTC by ladybug-tentoumushi

<概要>
## 目的
parsing.conbinatorを導入して構文解析できるようにしました。

## 確認方法
user@User MINGW64 ~/work/config-parse (parser)
$ sbt compile
[info] Loading global plugins from C:\Users\user\.sbt\1.0\plugins
[info] Loading project definition from C:\Users\user\work\config-parse\project
[info] Loading settings for project config-parse from build.sbt ...
[info] Set current project to config-parse (in build file:/C:/Users/user/work/config-parse/)
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 0 s, completed 2023/11/12 23:53:48

## 対応issue
https://github.com/ichikawapc/config-parse/issues/21

2023-11-12 23:13 UTC, ringospoon requested changes
build.sbt の変更もcommitしてもらえますでしょうか。

2023-11-13 23:32 UTC, ringospoon requested changes

2023-11-13 23:32 UTC, ringospoon commented on build.sbt
> +libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "2.3.0"
こまかいですが、
`libraryDependencies ...` の行が後ろの行になるように、行の順番いれかえてもらえますか？

2023-11-15 12:27 UTC, ladybug-tentoumushi commented on build.sbt
> +libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "2.3.0"
libraryDependencies ...を最後の行になるよう順番をいれかえました

2023-11-15 15:52 UTC, ringospoon approved these changes
LGTM

2023-11-15 15:52 UTC, merged