Section.scalaでリストをセクション名ごとにまとめるメソッドをつくりました
ichikawapc/config-parse pull request #33
Opened 2023-12-10 14:43 UTC by ladybug-tentoumushi

## 目的
リストをセクション名ごとにまとめられるようにする

## 確認方法
user@User MINGW64 ~/work/config-parse (make_section)
$ sbt run
[info] Loading global plugins from C:\Users\user\.sbt\1.0\plugins
[info] Loading settings for project config-parse-build from plugins.sbt ...
[info] Loading project definition from C:\Users\user\work\config-parse\project
[info] Loading settings for project config-parse from build.sbt ...
[info] Set current project to config-parse (in build file:/C:/Users/user/work/config-parse/)
[info] Compiling 1 Scala source to C:\Users\user\work\config-parse\target\scala-2.12\classes ...
[info] Done compiling.
[info] Compiling 1 Scala source to C:\Users\user\work\config-parse\target\scala-2.12\classes ...
[info] Done compiling.
[info] Packaging C:\Users\user\work\config-parse\target\scala-2.12\config-parse_2.12-0.1.0.jar ...
[info] Done packaging.
[info] Running Main
Hello World
List(Section(foo,List(report-name, user),List(Item(default,Map(report-name -> Summary)), Item(report2,Map(report-name -> Common, user -> admin)))), Section(bar,List(rule),List(Item(monitor,Map(rule -> none)))))
コマンドライン引数を与えて使ってね♡
使用例: sbt "run sample/input/bigip.conf"
[success] Total time: 6 s, completed 2023/12/10 23:37:36

## 関連 issue (ある場合は)
* https://github.com/ichikawapc/config-parse/issues/32

2023-12-12 01:39 UTC, ringospoon requested changes

2023-12-12 01:39 UTC, ringospoon commented on src/main/scala/Section.scala
> +import com.sun.tools.javac.jvm.Items
```
import com.sun.tools.javac.jvm.Items
```
これは不要なので消してください

2023-12-12 12:52 UTC, ladybug-tentoumushi commented on src/main/scala/Section.scala
> +import com.sun.tools.javac.jvm.Items
不要なimport文を削除しました

2023-12-12 13:07 UTC, ringospoon approved these changes
LGTM

2023-12-15 23:33 UTC, ladybug-tentoumushi commented
PR29をrebaseしました

2023-12-15 23:34 UTC, merged